// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How to represent the contract denomination
 */
public enum Bm2ContractRepresentationOption {
    /**
     * Use the symbols for clubs, diamonds, hearts and spades
     */
    UseSymbols(0),
    /**
     * Use letters for the denominations
     */
    UseLetter(1);

    private final int value;

    Bm2ContractRepresentationOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to UseSymbols instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2ContractRepresentationOption fromValue(int value) {
        for (Bm2ContractRepresentationOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return UseSymbols;
    }
}
