// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether and when the players can enter the handrecord for a board.
 */
public enum Bm2EnterHandrecordWhenOption {
    /**
     * The handrecord can be entered at the end of each round.
     */
    AtEndOfRound(0),
    /**
     * The handrecord can be entered after the play of each board.
     */
    AtEndOfBoard(1),
    /**
     * The handrecord cannot be entered.
     */
    DoNotEnter(2);

    private final int value;

    Bm2EnterHandrecordWhenOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to AtEndOfRound instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2EnterHandrecordWhenOption fromValue(int value) {
        for (Bm2EnterHandrecordWhenOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return AtEndOfRound;
    }
}
