// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies which source data should be consulted to look up player names for player numbers.
 */
public enum Bm2NameSource {
    /**
     * The PlayerNames table of the .bws scoring file.
     */
    PlayerNamesTable(0),
    /**
     * A separate MS-Access table.
     */
    BMPlayerDB(1),
    /**
     * No External source.
     */
    NoExternalSource(2),
    /**
     * First check the PlayerNames table then the external MS-Access file.
     */
    PlayerNamesTableThenBMPlayerDB(3);

    private final int value;

    Bm2NameSource(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to PlayerNamesTable instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2NameSource fromValue(int value) {
        for (Bm2NameSource member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return PlayerNamesTable;
    }
}
