// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies for which organization an entered playernumber should be validated.
 */
public enum Bm2NumberValidationOption {
    /**
     * No validation.
     */
    NoValidation(0),
    /**
     * Validate for the ACBL (USA).
     */
    ACBL(1),
    /**
     * Validate for the FFB (France).
     */
    FFB(2),
    /**
     * Validate for the ABF (Australia).
     */
    ABF(3),
    /**
     * Validate for the JCBL (Japanese).
     */
    JCBL(4);

    private final int value;

    Bm2NumberValidationOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to NoValidation instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2NumberValidationOption fromValue(int value) {
        for (Bm2NumberValidationOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return NoValidation;
    }
}
