// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies if the pairnumber should be part of entering the contract.
 */
public enum Bm2PairNumberEntryOption {
    /**
     * The pairnumber cannot be entered.
     */
    NoEntry(0),
    /**
     * The pairnumber entry is optional.
     */
    Optional(1),
    /**
     * The pairnumber entry is required.
     */
    Required(2);

    private final int value;

    Bm2PairNumberEntryOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to NoEntry instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2PairNumberEntryOption fromValue(int value) {
        for (Bm2PairNumberEntryOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return NoEntry;
    }
}
