// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Show the pointscore sign (plus or minus) from the perspective of declarer or North-South.
 */
public enum Bm2PointScorePerspectiveOption {
    /**
     * Show the pointscore sign (plus or minus) from the perspective of North-South.
     */
    FromNorthSouth(0),
    /**
     * Show the pointscore sign (plus or minus) from the perspective of declarer.
     */
    FromDeclarer(1);

    private final int value;

    Bm2PointScorePerspectiveOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to FromNorthSouth instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2PointScorePerspectiveOption fromValue(int value) {
        for (Bm2PointScorePerspectiveOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return FromNorthSouth;
    }
}
