// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How to enter the resulting tricks of a contract
 */
public enum BM2ResultEntryMethod {
    /**
     * The number of tricks above or below the level of the contract.
     */
    UpDownTricks(0),
    /**
     * The total number of tricks.
     */
    NumberOfTricks(1),
    /**
     * American style.
     */
    AmericanStyle(2);

    private final int value;

    BM2ResultEntryMethod(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to UpDownTricks instead of failing the whole response.
     */
    @JsonCreator
    public static BM2ResultEntryMethod fromValue(int value) {
        for (BM2ResultEntryMethod member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return UpDownTricks;
    }
}
