// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the results on a board should be formatted.
 */
public enum Bm2ResultsOverviewOption {
    /**
     * Group the results by pointscore and declarer: Max 6 lines, 1 column.
     */
    FrequencyList6lines1column(0),
    /**
     * Group the results by pointscore and declarer: Max 6 lines of 2 columns.
     */
    FrequencyList6lines2columns(1),
    /**
     * Group the results by pointscore and declarer: Max 4 lines, 1 column.
     */
    FrequencyList4lines1column(2),
    /**
     * Show the result for each couple of competing pairs: Max 6 lines, 1 column.
     */
    Traveler6lines1column(3),
    /**
     * Show the result for each couple of competing pairs: Max 6 lines, 2 columns.
     */
    Traveler6lines2columns(4),
    /**
     * Show the result for each couple of competing pairs: Max 4 lines, 1 column.
     */
    Traveler4lines1column(5);

    private final int value;

    Bm2ResultsOverviewOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to FrequencyList6lines1column instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2ResultsOverviewOption fromValue(int value) {
        for (Bm2ResultsOverviewOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return FrequencyList6lines1column;
    }
}
