// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether and how to show the summary points after the last round.
 */
public enum Bm2SummaryPointOption {
    /**
     * Show the scores as matchpoints.
     */
    Matchpoints(0),
    /**
     * Show the scores a percentages.
     */
    Percentage(1),
    /**
     * Do not show.
     */
    NoSummary(-1);

    private final int value;

    Bm2SummaryPointOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Matchpoints instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2SummaryPointOption fromValue(int value) {
        for (Bm2SummaryPointOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Matchpoints;
    }
}
