// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether and when to show the ranking.
 */
public enum Bm2ShowRankingOption {
    /**
     * Do not show.
     */
    DoNotShow(0),
    /**
     * Show the ranking after each round.
     */
    ShowAllRounds(1),
    /**
     * Show the ranking after the last round only.
     */
    ShowAfterLastRound(2);

    private final int value;

    Bm2ShowRankingOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to DoNotShow instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2ShowRankingOption fromValue(int value) {
        for (Bm2ShowRankingOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return DoNotShow;
    }
}
