// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether and when to show the names of the competing pairs.
 */
public enum Bm2ShowPlayerNamesOption {
    /**
     * Do not show.
     */
    DoNotShow(0),
    /**
     * Show in all rounds.
     */
    ShowInAllRounds(1),
    /**
     * Show in first round only.
     */
    ShowInFirstRoundOnly(2);

    private final int value;

    Bm2ShowPlayerNamesOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to DoNotShow instead of failing the whole response.
     */
    @JsonCreator
    public static Bm2ShowPlayerNamesOption fromValue(int value) {
        for (Bm2ShowPlayerNamesOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return DoNotShow;
    }
}
