// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies if a not played entry must be confirmed by the TD
 */
public enum Bm3ConfirmNPOption {
    /**
     * TD must not confirm Not Played
     */
    Disabled(0),
    /**
     * TD must confirm Not Played
     */
    Enabled(1);

    private final int value;

    Bm3ConfirmNPOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ConfirmNPOption fromValue(int value) {
        for (Bm3ConfirmNPOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
