// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether the Bridgemates for the section will work in online mode (continuous communication
 * with the Bridgemate 3 server) or if they work in offline mode (communication only at the start and
 * the end of the session).
 */
public enum Bm3ConnectionModeOption {
    /**
     * The Bridgemates for the section will work in online mode (continuous communication with the
     * Bridgemate 3 server).
     */
    Online(0),
    /**
     * The Bridgemates for the section will work in offline mode (communication will be initiated at
     * the end of the session or can be initiated manually).
     */
    Offline(1);

    private final int value;

    Bm3ConnectionModeOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Online instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ConnectionModeOption fromValue(int value) {
        for (Bm3ConnectionModeOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Online;
    }
}
