// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether and when handrecords can be entered by the players.
 */
public enum Bm3EnterHandrecordOption {
    /**
     * Handrecords cannot be entered by the players.
     */
    Disabled(0),
    /**
     * Handrecords can be entered after play of the board.
     */
    AtEndOfBoard(1),
    /**
     * Handrecords can be entered at the end of the round.
     */
    AtEndOfRound(2);

    private final int value;

    Bm3EnterHandrecordOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3EnterHandrecordOption fromValue(int value) {
        for (Bm3EnterHandrecordOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
