// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies which language should be used on the Bridgemate.
 */
public enum Bm3LanguageOption {
    /**
     * English
     */
    English(0),
    /**
     * Dutch
     */
    Dutch(1),
    /**
     * French
     */
    French(2),
    /**
     * German
     */
    German(3),
    /**
     * Italian
     */
    Italian(4),
    /**
     * Danish
     */
    Danish(5),
    /**
     * Spanish
     */
    Spanish(6),
    /**
     * Norwegian
     */
    Norwegian(7),
    /**
     * Polish
     */
    Polish(8),
    /**
     * Swedish
     */
    Swedish(9),
    /**
     * Turkish
     */
    Turkish(10);

    private final int value;

    Bm3LanguageOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to English instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3LanguageOption fromValue(int value) {
        for (Bm3LanguageOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return English;
    }
}
