// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether the lead card must be entered and how this will be validated.
 */
public enum Bm3LeadCardEntryOption {
    /**
     * No lead card entry.
     */
    Disabled(0),
    /**
     * The lead card must be entered. It will not be validated against the handrecord.
     */
    EnabledNoValidation(1),
    /**
     * The lead card must be entered. It will be validated against the handrecord and it must be
     * changed if validation fails.
     */
    EnabledWithValidationMustComply(2),
    /**
     * The lead card must be entered. It will be validated against the handrecord and a warning is
     * issued if validation fails.
     */
    EnabledWithValidationAllowNonCompliance(3);

    private final int value;

    Bm3LeadCardEntryOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3LeadCardEntryOption fromValue(int value) {
        for (Bm3LeadCardEntryOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
