// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether the tables for the next round should be displayed after the current round ends.
 */
public enum Bm3NextRoundSeatingOption {
    /**
     * Do not display the tables for the next round.
     */
    Disabled(0),
    /**
     * Display the tables for the next round after the current round ends.
     */
    Enabled(1);

    private final int value;

    Bm3NextRoundSeatingOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3NextRoundSeatingOption fromValue(int value) {
        for (Bm3NextRoundSeatingOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
