// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies how the wind rose player view is displayed
 */
public enum BM3PlayerViewOption {
    /**
     * players are displayed with north at the top
     */
    NorthOnTop(0),
    /**
     * players are displayed with north at the bottom
     */
    NorthOnTheBottom(1);

    private final int value;

    BM3PlayerViewOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to NorthOnTop instead of failing the whole response.
     */
    @JsonCreator
    public static BM3PlayerViewOption fromValue(int value) {
        for (BM3PlayerViewOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return NorthOnTop;
    }
}
