// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies wheter and when players can make themselves known.
 */
public enum Bm3PlayerRegistrationOption {
    /**
     * Player cannot make themselves known by entering their detaiils.
     */
    Disabled(0),
    /**
     * Player can make themselves known by entering their details in the first round only.
     */
    FirstRoundOnly(1),
    /**
     * Player can make themselves known by entering their details in all rounds.
     */
    AllRounds(2);

    private final int value;

    Bm3PlayerRegistrationOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3PlayerRegistrationOption fromValue(int value) {
        for (Bm3PlayerRegistrationOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
