// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether player can make themselves known once the round has started.
 */
public enum Bm3PlayerRegistrationOptionDuringPlay {
    /**
     * Players can make themselved known at the start of the round, before any result has been entered.
     */
    Disabled(0),
    /**
     * Players can make themselves known during any stage of the round.
     */
    Enabled(1);

    private final int value;

    Bm3PlayerRegistrationOptionDuringPlay(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3PlayerRegistrationOptionDuringPlay fromValue(int value) {
        for (Bm3PlayerRegistrationOptionDuringPlay member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
