// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether the result for a board can be changed after both pairs have confirmed it.
 */
public enum Bm3ResultReentryOption {
    /**
     * The result for a board cannot be changed after both pairs have confirmed it.
     */
    Disabled(0),
    /**
     * The result for a board can be changed after both pairs have confirmed it.
     */
    Enabled(1);

    private final int value;

    Bm3ResultReentryOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ResultReentryOption fromValue(int value) {
        for (Bm3ResultReentryOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
