// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether and when the ranking can be consulted.
 */
public enum Bm3RankingDisplayOption {
    /**
     * The ranking cannot be consulted.
     */
    Disabled(0),
    /**
     * The ranking can be consulted at the end of each round.
     */
    EndOfEachRound(1),
    /**
     * The ranking can be consulted at the end of the last round.
     */
    EndOfSession(2),
    /**
     * The ranking can be consulted at any moment.
     */
    Always(3);

    private final int value;

    Bm3RankingDisplayOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3RankingDisplayOption fromValue(int value) {
        for (Bm3RankingDisplayOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
