// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies how the number of tricks obtained must be entered.
 */
public enum Bm3ResultEntryMethod {
    /**
     * Enter the number of tricks obtained relative to the contract level.
     */
    UpDownTricks(0),
    /**
     * Enter the total number of tricks obtained.
     */
    NumberOfTricks(1),
    /**
     * Enter the number of tricks obtained American style.
     */
    AmericanStyle(2);

    private final int value;

    Bm3ResultEntryMethod(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to UpDownTricks instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ResultEntryMethod fromValue(int value) {
        for (Bm3ResultEntryMethod member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return UpDownTricks;
    }
}
