// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1040.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether starting positions should be confirmed by players at start of the session
 */
public enum BM3StartingPositionsOption {
    /**
     * Players cannot / may no confirm starting positions (NE/SW) at start of the session
     */
    Disabled(0),
    /**
     * Players must confirm starting positions (NE/SW) at start of the session
     */
    Enabled(1);

    private final int value;

    BM3StartingPositionsOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static BM3StartingPositionsOption fromValue(int value) {
        for (BM3StartingPositionsOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
