// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether session summaries are enabled or disabled.
 */
public enum Bm3SessionSummaryOption {
    /**
     * Indicates that the feature or functionality is disabled.
     */
    Disabled(0),
    /**
     * Indicates that the feature or functionality is enabled.
     */
    Enabled(1);

    private final int value;

    Bm3SessionSummaryOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3SessionSummaryOption fromValue(int value) {
        for (Bm3SessionSummaryOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
