// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1040.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies if there should be one column (for NS only) or two (for both NS and EW).
 */
public enum Bm3ScoreColumnOption {
    /**
     * Show one column, for NS.
     */
    NorthSouthOnly(0),
    /**
     * Shpw two columns, for NS and EW.
     */
    NorthSouthAndEastWest(1);

    private final int value;

    Bm3ScoreColumnOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to NorthSouthOnly instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ScoreColumnOption fromValue(int value) {
        for (Bm3ScoreColumnOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return NorthSouthOnly;
    }
}
