// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies if all the results obtained in the round can be consulted.
 */
public enum Bm3ScoreRecapOption {
    /**
     * The results obtained in the round cannot be consulted.
     */
    Disabled(0),
    /**
     * The results obtained in the round can be consulted at the end of the round only.
     */
    EnabledAtEndOfRoundOnly(1),
    /**
     * The results obtained in the round can be consulted at any time.
     */
    Always(2);

    private final int value;

    Bm3ScoreRecapOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ScoreRecapOption fromValue(int value) {
        for (Bm3ScoreRecapOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
