// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies of the players can call the TD using the Bridgemate.
 */
public enum Bm3TdCallOption {
    /**
     * The players cannot call the TD using the Bridgemate.
     */
    Disabled(0),
    /**
     * The players can call the TD using the Bridgemate.
     */
    Enabled(1);

    private final int value;

    Bm3TdCallOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3TdCallOption fromValue(int value) {
        for (Bm3TdCallOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
