// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies whether players can consult the handrecord for a board they just played.
 */
public enum Bm3ViewHandrecordOption {
    /**
     * Handrecords cannot be consulted.
     */
    Disabled(0),
    /**
     * Handrecords can be consulted after play of the board.
     */
    Enabled(1);

    private final int value;

    Bm3ViewHandrecordOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ViewHandrecordOption fromValue(int value) {
        for (Bm3ViewHandrecordOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
