// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies wheter to include the own score for a board in the result overview.
 */
public enum Bm3ViewPercentagesOption {
    /**
     * Do not include the own score for a board in the result overview.
     */
    Disabled(0),
    /**
     * Include the own score for a board in the result overview.
     */
    Enabled(1);

    private final int value;

    Bm3ViewPercentagesOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ViewPercentagesOption fromValue(int value) {
        for (Bm3ViewPercentagesOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
