// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1040.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies if other results on the board can be viewed.
 */
public enum Bm3ViewResultsOption {
    /**
     * Other results on the board cannot be viewed.
     */
    Disabled(0),
    /**
     * Only the own result can be viewed.
     */
    OwnResultOnly(1),
    /**
     * Other results, including the own results, on the board can be viewed.
     */
    OwnResultAndOtherResults(2),
    /**
     * Results shown at the end of the round in the board overview.
     */
    AtEndOfRound(3);

    private final int value;

    Bm3ViewResultsOption(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to Disabled instead of failing the whole response.
     */
    @JsonCreator
    public static Bm3ViewResultsOption fromValue(int value) {
        for (Bm3ViewResultsOption member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return Disabled;
    }
}
