// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Contains all settings for the Bridgemate 2 for a section. Mind that all values must be supplied.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Bridgemate2SettingsDTO extends BridgemateSettingsDTO {
    /**
     * Show results obtained on other rounds and on other tables.
     */
    @JsonProperty("ShowResults")
    public boolean showResults;

    /**
     * Include the own result in the results overview.
     */
    @JsonProperty("ShowOwnResult")
    public boolean showOwnResult;

    /**
     * Ask after showing the results if the overview should be repeated.
     */
    @JsonProperty("RepeatResults")
    public boolean repeatResults;

    /**
     * Show percentage rather than matchpoints.
     */
    @JsonProperty("ShowPercentage")
    public boolean showPercentage;

    /**
     * Currently not supported. Use the ScoringGroupDTO to group sections.
     */
    @JsonProperty("GroupSections")
    public boolean groupSections;

    /**
     * Show the point score of a result from the declarer's perspective or from that of North-South.
     */
    @JsonProperty("ScorePoints")
    public Bm2PointScorePerspectiveOption scorePoints = Bm2PointScorePerspectiveOption.FromNorthSouth;

    /**
     * Defines the way resulting tricks are enterd after the board has been played.
     */
    @JsonProperty("EnterResultsMethod")
    public BM2ResultEntryMethod enterResultsMethod = BM2ResultEntryMethod.UpDownTricks;

    /**
     * Determines if the pairnumbers are shown at the top of the Bridgemate.
     */
    @JsonProperty("ShowPairNumbers")
    public boolean showPairNumbers;

    /**
     * Currently not supported.
     */
    @JsonProperty("IntermediateResults")
    public boolean intermediateResults;

    /**
     * The time in seconds before the Bridgemate will power off.
     */
    @JsonProperty("AutopoweroffTime")
    public int autopoweroffTime;

    /**
     * The time in seconds that the message that the opponents must confirm the entered result is
     * shown.
     */
    @JsonProperty("VerificationTime")
    public int verificationTime;

    /**
     * Show the denomination of the contract as letters or as suit symbols.
     */
    @JsonProperty("ShowContract")
    public Bm2ContractRepresentationOption showContract = Bm2ContractRepresentationOption.UseSymbols;

    /**
     * Defines if the leadcard should be entered.
     */
    @JsonProperty("LeadCard")
    public boolean leadCard;

    /**
     * If ShowResults is "True" determines the maximum number of results that will be shown.
     */
    @JsonProperty("MaximumResults")
    public int maximumResults;

    /**
     * Defines if the players can make themselves know by entering their player number on the
     * Bridgemate.
     */
    @JsonProperty("MemberNumbers")
    public boolean memberNumbers;

    /**
     * If "True" all players must have been identified by their player number.
     */
    @JsonProperty("MemberNumbersNoBlankEntry")
    public boolean memberNumbersNoBlankEntry;

    /**
     * Defines if the Bridgemate should check the order of play.
     */
    @JsonProperty("BoardOrderVerification")
    public boolean boardOrderVerification;

    /**
     * Currently not supported.
     */
    @JsonProperty("HandRecordValidation")
    public boolean handRecordValidation;

    /**
     * Defines if BCS should automatically shut down when all results are in.
     */
    @JsonProperty("AutoShutDownBPC")
    public boolean autoShutDownBPC;

    /**
     * The pincode that the TD must enter before accessing the TD menu on the Bridgemate. Must be four
     * digits.
     */
    @JsonProperty("BM2PINcode")
    public String bM2PINcode;

    /**
     * Defines if the TD must confirm No Play on the Bridgemate.
     */
    @JsonProperty("BM2ConfirmNP")
    public boolean bM2ConfirmNP;

    /**
     * Defines if the Bridgemate should show how many boards in the round are left to play.
     */
    @JsonProperty("BM2RemainingBoards")
    public boolean bM2RemainingBoards;

    /**
     * Defines if the Bridgemate should show the seatings for the next round.
     */
    @JsonProperty("BM2NextSeatings")
    public boolean bM2NextSeatings;

    /**
     * Defines if the Bridgemate can show the scores obtained during the round when a player presses
     * the appropriate button on the Bridgemate.
     */
    @JsonProperty("BM2ScoreRecap")
    public boolean bM2ScoreRecap;

    /**
     * Defines if the Bridgemate should show the score recap wihtout promptimg after the last board of
     * the round has been played..
     */
    @JsonProperty("BM2AutoShowScoreRecap")
    public boolean bM2AutoShowScoreRecap;

    /**
     * Defines if the players can correct scores themselves. If not the TD must be called to the table
     * to do this.
     */
    @JsonProperty("BM2ScoreCorrection")
    public boolean bM2ScoreCorrection;

    /**
     * Defines if the Brigemate should enter the board number automatically..
     */
    @JsonProperty("BM2AutoBoardNumber")
    public boolean bM2AutoBoardNumber;

    /**
     * If BM2AutoBoardNumber is "True" defines if the boardnumber of the first board should be entered
     * manually. The subsequent boards will be filled in automatically.
     */
    @JsonProperty("BM2FirstBoardManually")
    public boolean bM2FirstBoardManually;

    /**
     * Determines if the entry of the leadcard should be checked against the handrecord.
     */
    @JsonProperty("BM2ValidateLeadCard")
    public boolean bM2ValidateLeadCard;

    /**
     * Determines how the results overview will be formatted on the display.
     */
    @JsonProperty("BM2ResultsOverview")
    public Bm2ResultsOverviewOption bM2ResultsOverview = Bm2ResultsOverviewOption.FrequencyList6lines1column;

    /**
     * Determines if the Bridgemate shows the names of the players and if so at the start of each round
     * or in the first round only.
     */
    @JsonProperty("BM2ShowPlayerNames")
    public Bm2ShowPlayerNamesOption bM2ShowPlayerNames = Bm2ShowPlayerNamesOption.DoNotShow;

    /**
     * Determines if the Bridgemate should show the ranking and if so after play of the last board of a
     * round or after play of the last board of the session..
     */
    @JsonProperty("BM2Ranking")
    public Bm2ShowRankingOption bM2Ranking = Bm2ShowRankingOption.DoNotShow;

    /**
     * Enable/disable the summary after end of session. (Enabled requires BM2Ranking=1 or 2
     */
    @JsonProperty("BM2GameSummary")
    public boolean bM2GameSummary;

    /**
     * Defines if matchpoints or the percentage should be shown in the game summary.
     */
    @JsonProperty("BM2SummaryPoints")
    public Bm2SummaryPointOption bM2SummaryPoints = Bm2SummaryPointOption.Matchpoints;

    /**
     * Defines if the players can or must enter the pair number when entering the declaring side for a
     * contract. Enforcing this helps in detecting switched seatings.
     */
    @JsonProperty("BM2PairNumberEntry")
    public Bm2PairNumberEntryOption bM2PairNumberEntry = Bm2PairNumberEntryOption.NoEntry;

    /**
     * Determines if the "Reset" key is available to the players, rather than to the TD only.
     */
    @JsonProperty("BM2ResetFunctionKey")
    public boolean bM2ResetFunctionKey;

    /**
     * Currently not supported.
     */
    @JsonProperty("BM2RecordBidding")
    public boolean bM2RecordBidding;

    /**
     * Currently not supported.
     */
    @JsonProperty("BM2RecordPlay")
    public boolean bM2RecordPlay;

    /**
     * Currently not supported.
     */
    @JsonProperty("BM2ValidateRecording")
    public boolean bM2ValidateRecording;

    /**
     * Currently not suppoorted.
     */
    @JsonProperty("BM2ShowHands")
    public boolean bM2ShowHands;

    /**
     * Currently not supported
     */
    @JsonProperty("NumberValidation")
    public Bm2NumberValidationOption numberValidation = Bm2NumberValidationOption.NoValidation;

    /**
     * Defines if the players must enter their player number each round.
     */
    @JsonProperty("BM2NumberEntryEachRound")
    public boolean bM2NumberEntryEachRound;

    /**
     * Currently not supported.
     */
    @JsonProperty("BM2NumberEntryPreloadValues")
    public boolean bM2NumberEntryPreloadValues;

    /**
     * Currently not supported.
     */
    @JsonProperty("BM2NameSource")
    public Bm2NameSource bM2NameSource = Bm2NameSource.PlayerNamesTable;

    /**
     * Determines if the players can see the handrecord of the board they just played.
     */
    @JsonProperty("BM2ViewHandRecord")
    public boolean bM2ViewHandRecord;

    /**
     * Determines if the players can enter the handrecord for boards they played if not present.
     */
    @JsonProperty("BM2EnterHandRecord")
    public boolean bM2EnterHandRecord;

    /**
     * If BM2EnterHandRecord is "True" determines if the players can enter the handrecord after play of
     * the board or after playing all boards for the round.
     */
    @JsonProperty("BM2EnterHandRecordWhen")
    public Bm2EnterHandrecordWhenOption bM2EnterHandRecordWhen = Bm2EnterHandrecordWhenOption.AtEndOfRound;

    /**
     * Currently not supported.
     */
    @JsonProperty("BM2TextBasedNumber")
    public boolean bM2TextBasedNumber;

    /**
     * Defines if the "Call TD" button is visible on the Bridgemate.
     */
    @JsonProperty("BM2TDCall")
    public boolean bM2TDCall;
}
