// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The base class for the Bridgemate2SettingsDTO and the Bridgemate3SettingsDTO
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public abstract class BridgemateSettingsDTO {
    /**
     * Required. Specifies the guid of the session for which the settings apply.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required. Specifies for which section the settings apply.
     */
    @JsonProperty("SectionLetters")
    public String sectionLetters;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
