// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Contains all settings for the Bridgemate 3 for a section. Mind that all values must be supplied.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Bridgemate3SettingsDTO extends BridgemateSettingsDTO {
    /**
     * Valid values 1-7. Defines the screen brightness.
     */
    @JsonProperty("BM3ScreenBrightness")
    public int bM3ScreenBrightness;

    /**
     * Valid values 0-15. Defines the number of seconds(times 5) before the screen of the Bridgemate
     * will dim.So the default value of 2 amounts to 10 seconds.
     */
    @JsonProperty("BM3ScreenDimMode")
    public int bM3ScreenDimMode;

    /**
     * Valid values 0-15. Defines the number of seconds (times 5) before the screen of the Bridgemate
     * will turn off. A value of zero, the default, means "never turn off".
     */
    @JsonProperty("BM3ScreenOffMode")
    public int bM3ScreenOffMode;

    /**
     * Valid values 0-120. Defines the number of seconds (times 5) before the Bridgemate will enter
     * Sleepmode. Once the Bridgemate has entered sleepmode its powerbutton must be used to wake it up
     * again.
     */
    @JsonProperty("BM3SleepMode")
    public int bM3SleepMode;

    /**
     * Valid values 0-7. Currently not in use.
     */
    @JsonProperty("BM3AudioVolume")
    public int bM3AudioVolume;

    /**
     * Specifies which language the Bridgemate will use. The default is zero for English.
     */
    @JsonProperty("BM3Language")
    public Bm3LanguageOption bM3Language = Bm3LanguageOption.English;

    /**
     * Must be four digits. The code the TD must enter to get access to the TD menu. Defaults to
     * "0000".
     */
    @JsonProperty("BM3PINcode")
    public String bM3PINcode;

    /**
     * Specifies if the TD must confirm a "Not Played". Default Off
     */
    @JsonProperty("BM3ConfirmNP")
    public Bm3ConfirmNPOption bM3ConfirmNP = Bm3ConfirmNPOption.Disabled;

    /**
     * Specifies if players can call for the Tournament Director using the Bridgemate.
     */
    @JsonProperty("BM3TDCall")
    public Bm3TdCallOption bM3TDCall = Bm3TdCallOption.Disabled;

    /**
     * Specifies how players can enter the result for a board: Up/Down tricks, total tricks or American
     * style.
     */
    @JsonProperty("BM3ResultMethod")
    public Bm3ResultEntryMethod bM3ResultMethod = Bm3ResultEntryMethod.UpDownTricks;

    /**
     * Specifies if players may reenter the result of the board after the original entry has been
     * confirmed by the opponents.
     */
    @JsonProperty("BM3BoardResultReentry")
    public Bm3ResultReentryOption bM3BoardResultReentry = Bm3ResultReentryOption.Disabled;

    /**
     * Specifies if the leadcard must be enterd together with the contract and if the leadcard should
     * be validated againts the handrecord.
     */
    @JsonProperty("BM3LeadCardEntry")
    public Bm3LeadCardEntryOption bM3LeadCardEntry = Bm3LeadCardEntryOption.Disabled;

    /**
     * Specifies if and when the players can make themselves known by entering their playernumber
     * and/or name on the Bridgemate.
     */
    @JsonProperty("BM3PlayerNumberEntry")
    public Bm3PlayerRegistrationOption bM3PlayerNumberEntry = Bm3PlayerRegistrationOption.Disabled;

    /**
     * Specifies if and when the players can make themselves known by entering their playernumber
     * and/or name on the Bridgemate while the round is in progress (i.e.: after a board has been
     * entered).
     */
    @JsonProperty("BM3PlayerNumberEntryDuringPlay")
    public Bm3PlayerRegistrationOptionDuringPlay bM3PlayerNumberEntryDuringPlay = Bm3PlayerRegistrationOptionDuringPlay.Disabled;

    /**
     * Specifies if players must identify themselves at the start of the session by entering their
     * playernumber.
     */
    @JsonProperty("BM3PlayerNumberMandatory")
    public Bm3PlayerNumberMandatoryOption bM3PlayerNumberMandatory = Bm3PlayerNumberMandatoryOption.Disabled;

    /**
     * Specifies whether starting positions should be confirmed by players at start of the session
     */
    @JsonProperty("BM3StartingPositions")
    public BM3StartingPositionsOption bM3StartingPositions = BM3StartingPositionsOption.Disabled;

    /**
     * Specifies how the wind rose player view is displayed
     */
    @JsonProperty("BM3PlayerView")
    public BM3PlayerViewOption bM3PlayerView = BM3PlayerViewOption.NorthOnTop;

    /**
     * Specifies if and when the Bridgemate will show the current ranking for the players on the table.
     */
    @JsonProperty("BM3Ranking")
    public Bm3RankingDisplayOption bM3Ranking = Bm3RankingDisplayOption.Disabled;

    /**
     * Specifes if the seatings for the next round must be displayed after the last result has been
     * entered for the round.
     */
    @JsonProperty("BM3NextSeatings")
    public Bm3NextRoundSeatingOption bM3NextSeatings = Bm3NextRoundSeatingOption.Disabled;

    /**
     * Specifies if and when the Bridgemate will show a recap of the scores obtained on the table in
     * the current round.
     */
    @JsonProperty("BM3ScoreRecap")
    public Bm3ScoreRecapOption bM3ScoreRecap = Bm3ScoreRecapOption.Disabled;

    /**
     * Specifies if the Bridgemate will show the other results for the board that was just entered.
     */
    @JsonProperty("BM3ViewResults")
    public Bm3ViewResultsOption bM3ViewResults = Bm3ViewResultsOption.Disabled;

    /**
     * Specifies if the Bridgemate will show a session summary with all the scores obtained in the
     * session once the session has ended.
     */
    @JsonProperty("BM3SessionSummary")
    public Bm3SessionSummaryOption bM3SessionSummary = Bm3SessionSummaryOption.Disabled;

    /**
     * Specifies if the score columns should be for NS only (one column) or for NS and EW (two columns)
     */
    @JsonProperty("BM3ScoreColum")
    public Bm3ScoreColumnOption bM3ScoreColum = Bm3ScoreColumnOption.NorthSouthOnly;

    /**
     * Specifies if the own percentage should be included in the results overview.
     */
    @JsonProperty("BMViewPercentages")
    public Bm3ViewPercentagesOption bMViewPercentages = Bm3ViewPercentagesOption.Disabled;

    /**
     * Specifies if players may view the handrecord after the result has been entered.
     */
    @JsonProperty("BM3ViewHandrecord")
    public Bm3ViewHandrecordOption bM3ViewHandrecord = Bm3ViewHandrecordOption.Disabled;

    /**
     * Specifies if and when the players can enter the handrecord for a board if it is not present.
     */
    @JsonProperty("BM3EnterHandrecord")
    public Bm3EnterHandrecordOption bM3EnterHandrecord = Bm3EnterHandrecordOption.Disabled;
}
