// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Instructs BCS to continue working with a previously created event using the
 * ScoringProgramPipeClient.Continue method or the ScoringProgramPipeClient.ContinueAsync method.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ContinueDTO {
    /**
     * Tells BCS which event to continue. When there is only one session the event guid will be its
     * session guid unless it was set to a different value in the original InitDTO.
     */
    @JsonProperty("EventGuid")
    public String eventGuid;

    /**
     * Required when using the http interface for the dataconnector
     */
    @JsonProperty("ClubId")
    public String clubId;

    /**
     * 1: Just start BCS and let it reconnect to the last used scoring file if it contains a session
     * with the correct guid. 5: Start BCS, let it reconnect and start reading. add 128: clear all
     * previous data from the Data Connector.
     */
    @JsonProperty("Commands")
    public int commands;

    /**
     * Optional. Specifies a different directory for the BCS scoring file. Only use in advanced
     * scenarios. If used make sure that the directory exists.
     */
    @JsonProperty("AlternativeDataFolder")
    public String alternativeDataFolder;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
