// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies the data type that the ScoringProgramResponse's SerializedData property should contain.
 */
public enum DataConnectorResponseData {
    /**
     * There is no accompanying data.
     */
    None(0),
    /**
     * Acknowledges a command that does not return data
     */
    OK(1),
    /**
     * Not in use.
     */
    Paused(2),
    /**
     * Signals a non essential error.
     */
    Warning(3),
    /**
     * Signals that an error occurred. The accompanying data will be a serialized string explaining the
     * error.
     */
    Error(4),
    /**
     * Data to create a new event. An InitDTO.
     */
    InitData(5),
    /**
     * Data to continue a previously created event. A ContinueDTO.
     */
    ContinueData(6),
    /**
     * Data to update sections and their scoringgroups. A collection of ScoringGroupDTO.
     */
    SectionData(7),
    /**
     * Data to update the BM2 settings. A Bridgemate2SettingsDTO.
     */
    Bridgemate2Settings(8),
    /**
     * Data to update the BM3 settings. A Bridgemate2SettingsDTO.
     */
    Bridgemate3Settings(9),
    /**
     * First name, last name, country code for players. A PlayerDataDTO.
     */
    PlayerData(10),
    /**
     * Position of players at a table in a round. A ParticipationDTO.
     */
    Participations(11),
    /**
     * Boardresults. A collection of ResultDTO.
     */
    Results(12),
    /**
     * Handrecords. A collection of HandrecordDTO.
     */
    Handrecords(13),
    /**
     * Data to update the movement for a section. A SectionDTO.
     */
    Movement(14),
    /**
     * Data for a new session. A SectionDTO.
     */
    Session(15),
    /**
     * Sessions, their scoringroups and their sections. A BCSManagementResponseDTO with an array of
     * SessionInfoDTOs as its SessionInformation property.
     */
    Sessions(16),
    /**
     * Guid-name pairs of the sessions currently being administered. Embedded in a
     * BCSManagementResponseDTO.
     */
    EventInfo(17),
    /**
     * Guid-name-scoringfile location for all sessions that are present in BCS' data. Embedded in a
     * BCSManagementResponseDTO.
     */
    AllSessionsInfo(18),
    /**
     * The location of the scoring file for BCS. Embedded in a BCSManagementResponseDTO.
     */
    ScoringFileLocation(19),
    /**
     * The data is a shutdown request. Embedded in a BCSManagementRequesetDTO.
     */
    ShutDownRequest(20),
    /**
     * A collection of td calls. TdCallDTO/>
     */
    TdCalls(21),
    /**
     * Currently not supported.
     */
    TestData(22);

    private final int value;

    DataConnectorResponseData(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to None instead of failing the whole response.
     */
    @JsonCreator
    public static DataConnectorResponseData fromValue(int value) {
        for (DataConnectorResponseData member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return None;
    }
}
