// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1037.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Clarifies what type of error occurred, causing the ScoringProgramRequest to fail.
 */
public enum ErrorType {
    /**
     * The is no error.
     */
    None(0),
    /**
     * The Data Connector was handling an other request.
     */
    Busy(1),
    /**
     * The sent data was null or did not contain any elements while the request command should come
     * with data.
     */
    NoData(2),
    /**
     * Signals that sent data that meant to update exisiting data already existed.
     */
    NoUpdates(3),
    /**
     * The sent data did not comply to a known round on a table.
     */
    Movement(4),
    /**
     * The dto has invalid data.
     */
    Validation(5),
    /**
     * No record for the given primary key was found.
     */
    EntryUnknown(6),
    /**
     * An error occurred when processing the data.
     */
    Exception(7),
    /**
     * The requested operation is currently not supported.
     */
    NotImplemented(8),
    /**
     * A meaningful response to the request was exptected, but an empty response came back.
     */
    EmptyResponse(9),
    /**
     * The connection to the Data Connector is broken.
     */
    NoConnection(10),
    /**
     * The operation was blocked by a previous long running operation.
     */
    TimeOut(11),
    /**
     * The datatype of the dtos did not conform to the request command.
     */
    WrongDataType(12),
    /**
     * The response command did not conform to the request command.
     */
    UnexpectedCommand(13),
    /**
     * Unknown error.
     */
    Unknown(14);

    private final int value;

    ErrorType(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to None instead of failing the whole response.
     */
    @JsonCreator
    public static ErrorType fromValue(int value) {
        for (ErrorType member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return None;
    }
}
