// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Contains the data for a handrecord and optionally its double dummy values.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class HandrecordDTO {
    /**
     * Required. The guid of the session the handrecord belongs to. A string built from a Guid, without
     * the curly braces or connecting dashes. The letters must be capitals. Must be unique
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required. The number of the scoringgroup that the handrecord belongs to.
     */
    @JsonProperty("ScoringGroupNumber")
    public int scoringGroupNumber;

    /**
     * Required, any of the sections that are part of the scoringgroup.
     */
    @JsonProperty("SectionLetters")
    public String sectionLetters;

    /**
     * Required. Must be greater than zero.
     */
    @JsonProperty("BoardNumber")
    public int boardNumber;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("NorthClubs")
    public String northClubs;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("NorthDiamonds")
    public String northDiamonds;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("NorthHearts")
    public String northHearts;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("NorthSpades")
    public String northSpades;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("EastClubs")
    public String eastClubs;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("EastDiamonds")
    public String eastDiamonds;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("EastHearts")
    public String eastHearts;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("EastSpades")
    public String eastSpades;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("SouthClubs")
    public String southClubs;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("SouthDiamonds")
    public String southDiamonds;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("SouthHearts")
    public String southHearts;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("SouthSpades")
    public String southSpades;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("WestClubs")
    public String westClubs;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("WestDiamonds")
    public String westDiamonds;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("WestHearts")
    public String westHearts;

    /**
     * Valid card values are AKQJT98765432 Indicate a void with an empty string. Null will be
     * disqualified.
     */
    @JsonProperty("WestSpades")
    public String westSpades;

    /**
     * It "True" the double dummy values will be processed by the Data Connector.
     */
    @JsonProperty("HasHandEvaluationData")
    public boolean hasHandEvaluationData;

    /**
     * The number of tricks that can be made with North as declarer and Clubs as denomination.
     */
    @JsonProperty("DoubleDummyNorthClubs")
    public int doubleDummyNorthClubs;

    /**
     * The number of tricks that can be made with North as declarer and Diamonds as denomination.
     */
    @JsonProperty("DoubleDummyNorthDiamonds")
    public int doubleDummyNorthDiamonds;

    /**
     * The number of tricks that can be made with North as declarer and Hearts as denomination.
     */
    @JsonProperty("DoubleDummyNorthHearts")
    public int doubleDummyNorthHearts;

    /**
     * The number of tricks that can be made with North as declarer and Spades as denomination.
     */
    @JsonProperty("DoubleDummyNorthSpades")
    public int doubleDummyNorthSpades;

    /**
     * The number of tricks that can be made with North as declarer and No Trump as denomination.
     */
    @JsonProperty("DoubleDummyNorthNoTrump")
    public int doubleDummyNorthNoTrump;

    /**
     * The number of tricks that can be made with East as declarer and Clubs as denomination.
     */
    @JsonProperty("DoubleDummyEastClubs")
    public int doubleDummyEastClubs;

    /**
     * The number of tricks that can be made with East as declarer and Diamonds as denomination.
     */
    @JsonProperty("DoubleDummyEastDiamonds")
    public int doubleDummyEastDiamonds;

    /**
     * The number of tricks that can be made with East as declarer and Hearts as denomination.
     */
    @JsonProperty("DoubleDummyEastHearts")
    public int doubleDummyEastHearts;

    /**
     * The number of tricks that can be made with East as declarer and Spades as denomination.
     */
    @JsonProperty("DoubleDummyEastSpades")
    public int doubleDummyEastSpades;

    /**
     * The number of tricks that can be made with East as declarer and No Trump as denomination.
     */
    @JsonProperty("DoubleDummyEastNoTrump")
    public int doubleDummyEastNoTrump;

    /**
     * The number of tricks that can be made with South as declarer and Clubs as denomination.
     */
    @JsonProperty("DoubleDummySouthClubs")
    public int doubleDummySouthClubs;

    /**
     * The number of tricks that can be made with South as declarer and Diamonds as denomination.
     */
    @JsonProperty("DoubleDummySouthDiamonds")
    public int doubleDummySouthDiamonds;

    /**
     * The number of tricks that can be made with South as declarer and Hearts as denomination.
     */
    @JsonProperty("DoubleDummySouthHearts")
    public int doubleDummySouthHearts;

    /**
     * The number of tricks that can be made with South as declarer and Spades as denomination.
     */
    @JsonProperty("DoubleDummySouthSpades")
    public int doubleDummySouthSpades;

    /**
     * The number of tricks that can be made with South as declarer and No Trump as denomination.
     */
    @JsonProperty("DoubleDummySouthNoTrump")
    public int doubleDummySouthNoTrump;

    /**
     * The number of tricks that can be made with West as declarer and Clubs as denomination.
     */
    @JsonProperty("DoubleDummyWestClubs")
    public int doubleDummyWestClubs;

    /**
     * The number of tricks that can be made with West as declarer and Diamonds as denomination.
     */
    @JsonProperty("DoubleDummyWestDiamonds")
    public int doubleDummyWestDiamonds;

    /**
     * The number of tricks that can be made with West as declarer and Hearts as denomination.
     */
    @JsonProperty("DoubleDummyWestHearts")
    public int doubleDummyWestHearts;

    /**
     * The number of tricks that can be made with West as declarer and Spades as denomination.
     */
    @JsonProperty("DoubleDummyWestSpades")
    public int doubleDummyWestSpades;

    /**
     * The number of tricks that can be made with West as declarer and No Trump as denomination.
     */
    @JsonProperty("DoubleDummyWestNoTrump")
    public int doubleDummyWestNoTrump;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
