// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Contains information on how to construct a new event, with its sessions, sections, tables and
 * rounds. Optionally player data, participations and handrecords can be added. Doing this is more
 * performant than adding them later. Is used as a parameter for the
 * ScoringProgramPipeClient.Initialize or the ScoringProgramPipeClient.InitializeAsync method.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class InitDTO {
    /**
     * Instructs the Data Connector to start BCS.
     */
    public static final int StartBCS = 1;

    /**
     * Instructs BCS to create a new event from the data in this DTO.
     */
    public static final int Command_Reset = 2;

    /**
     * Instructs BCS to start reading from the Data Connector.
     */
    public static final int Command_StartReading = 4;

    /**
     * Instructs BCS to upload the sessions to the Bridgemate App server.
     */
    public static final int Command_ShowInApp = 8;

    /**
     * Instructs BCS to start minimized.
     */
    public static final int Command_Minimize = 16;

    /**
     * Instructs BCS to shut down after the last result has been processed.
     */
    public static final int Command_AutoShutDownBPC = 32;

    /**
     * Sets the log level to "Debug" rather than "Info".
     */
    public static final int Command_LogLevel_Debug = 64;

    /**
     * Instructs the Data Connector to clear all its previous data and start with a clean slate.
     */
    public static final int Command_ClearData = 128;

    /**
     * Instructs the Data Connector to use communicate over http.
     */
    public static final int Command_UseHttp = 256;

    /**
     * Instructions to BCS. Add up the values to combine. 1. Start BCS (if not already started). 2:
     * Reset the Bridgemates (and App) and fill them with the provided data. 4: Start Reading from the
     * Bridgemates, Data Connector (and App). 8: Upload the sessions to the app. 16: Minimize BCS
     * 32:Close BCS when all results have been processed. 64: Lower the logging level from "Info" to
     * "Debug". 128:Clear all previous data from the Data Connector queue.
     */
    @JsonProperty("Commands")
    public int commands;

    /**
     * Required if the number of sessions is greater than one. This signals that BCS should administer
     * these sessions together.
     */
    @JsonProperty("EventGuid")
    public String eventGuid;

    /**
     * Required when using http for communication with the data connector.
     */
    @JsonProperty("ClubId")
    public String clubId;

    /**
     * Optional. Specifies a different directory for the BCS scoring file. Only use in advanced
     * scenarios. If used make sure that the directory exists.
     */
    @JsonProperty("AlternativeDataFolder")
    public String alternativeDataFolder;

    /**
     * Required, must be at least one.
     */
    @JsonProperty("Sessions")
    public SessionDTO[] sessions;

    /**
     * Optional: the data of at least the players that will participate in the sessions. Player data is
     * required for every participation that has its a SessionGuid and PlayerNumber properties set.
     */
    @JsonProperty("PlayerData")
    public PlayerDataDTO[] playerData;

    /**
     * Optional. Each participation with its SessionGuid and PlayerNumber properties set must have a
     * corresponding player data element that specifies at least its name.
     */
    @JsonProperty("Participations")
    public ParticipationDTO[] participations;

    /**
     * Optional. The handrecords for each session.
     */
    @JsonProperty("Handrecords")
    public HandrecordDTO[] handrecords;

    /**
     * Optional. The settings for the Bridgemate 2 for all sections (if in use).
     */
    @JsonProperty("Bridgemate2Settings")
    public Bridgemate2SettingsDTO[] bridgemate2Settings;

    /**
     * Optional. The settings for the Bridgemate 3 for all sections (if in use).
     */
    @JsonProperty("Bridgemate3Settings")
    public Bridgemate3SettingsDTO[] bridgemate3Settings;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
