// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class can be used: 1. To give names for the players in the first round by only specifying their
 * player numbers. For this to work the names belonging to the playernumber must have been passed first
 * using PlayerDTO's. 2. To give names for the players in the first round by omitting their
 * playernumber. In this case the players will be registerd for this session only. The combination of
 * both playernumber and name details is not supported.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ParticipationDTO {
    /**
     * Required. The guid of the session the participation belongs to. A string built from a Guid,
     * without the curly braces or connecting dashes. The letters must be capitals
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required. The letters of the section the participation belongs to. Can be A-Z, AA, BB, CC,...ZZ,
     * AAA, BBB, CCC, ... ZZZ
     */
    @JsonProperty("SectionLetters")
    public String sectionLetters;

    /**
     * Required. The number of the table for the player in the round.
     */
    @JsonProperty("TableNumber")
    public int tableNumber;

    /**
     * Required. The position on the table for the player in the round. 1: North 2: East 3: South 4:
     * West
     */
    @JsonProperty("Direction")
    public TableDirection direction = TableDirection.None;

    /**
     * Currently only the values zero and one are supported. They are treated the same as the table
     * where the player sits in the first round. Optional, specifying a number higher than 1 indicates
     * that the name of the player has become known in a latter round. BCS will use the known movement
     * to calculate the player's positions in other rounds.
     */
    @JsonProperty("RoundNumber")
    public int roundNumber;

    /**
     * Optional, but must be present together with the SessionGuid if no name details are passed. The
     * playernumber must have been passed beforehand using a PlayerDTO containg the name details.
     */
    @JsonProperty("PlayerNumber")
    public String playerNumber;

    /**
     * Signals that this player was swapped with his partner: North was swapped with South, or East
     * with West.
     */
    @JsonProperty("IsPlayerSwap")
    public boolean isPlayerSwap;

    /**
     * Optional, must only be used when the playernumber is empty.
     */
    @JsonProperty("FirstName")
    public String firstName;

    /**
     * Required when the playernumber is empty.Must only be used when the playernumber is empty.
     */
    @JsonProperty("LastName")
    public String lastName;

    /**
     * Optional, must only be used when the playernumber is empty.
     */
    @JsonProperty("CountryCode")
    public String countryCode;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
