// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class carries information on a player: name, country and playernumber. Each ParticipationDTO
 * carrying a non empty playernumber property must have a corresponding PlayerDataDTO woith the given
 * playernumber (and SessionGuid) that was sent before the ParticipationDTO was sent.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class PlayerDataDTO {
    /**
     * Required, the guid of the session the player participates in.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required when using the http interface for the dataconnector
     */
    @JsonProperty("ClubId")
    public String clubId;

    /**
     * Required, must uniquely identify the player within the session.
     */
    @JsonProperty("PlayerNumber")
    public String playerNumber;

    /**
     * Optional
     */
    @JsonProperty("FirstName")
    public String firstName;

    /**
     * Required
     */
    @JsonProperty("LastName")
    public String lastName;

    /**
     * Optional
     */
    @JsonProperty("CountryCode")
    public String countryCode;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
