// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class carries information on the result of a board that was played in a specific round on a
 * specific table. The Level property is also used to express "No Play" and artificial results (using
 * negative values).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ResultDTO {
    /**
     * The result pertains to North-South only. i.e.: The East-West pair may have a different result
     * and a ResultDTO with its ScoringDirection property set to ScoringDirection_EW must be provided.
     */
    public static final int ScoringDirection_NS = 1;

    /**
     * The result pertains to East-West only. i.e.: The North-South pair may have a different result
     * and a ResultDTO with its ScoringDirection property set to ScoringDirection_NS must be provided.
     */
    public static final int ScoringDirection_EW = 2;

    /**
     * The result pertains to both North-South and East-West.
     */
    public static final int ScoringDirection_NSEW = 3;

    /**
     * The denomination of the contract is Clubs.
     */
    public static final int Denomination_Clubs = 1;

    /**
     * The denomination of the contract is Diamonds.
     */
    public static final int Denomination_Diamonds = 2;

    /**
     * The denomination of the contract is Hearts.
     */
    public static final int Denomination_Hearts = 3;

    /**
     * The denomination of the contract is Spades.
     */
    public static final int Denomination_Spades = 4;

    /**
     * The denomination of the contract is No Trump.
     */
    public static final int Denomination_NoTrump = 5;

    /**
     * Declarer is the player on the North seat.
     */
    public static final int Direction_North = 1;

    /**
     * Declarer is the player on the East seat.
     */
    public static final int Direction_East = 2;

    /**
     * Declarer is the player on the South seat.
     */
    public static final int Direction_South = 3;

    /**
     * Declarer is the player on the West seat.
     */
    public static final int Direction_West = 4;

    /**
     * The contract of the board was "Pass".
     */
    public static final int ContractLevel_Pass = 0;

    /**
     * The board was not played.
     */
    public static final int ContractLevel_NoPLay = -10;

    /**
     * The contract was not doubled or redoubled.
     */
    public static final int Stake_Normal = 0;

    /**
     * The contract was doubled.
     */
    public static final int Stake_Doubled = 1;

    /**
     * The contract was redoubled.
     */
    public static final int Stake_Redoubled = 2;

    /**
     * An artificial score of Average Minus for the North-South pair and Average Minus for the
     * East-West pair if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW.
     * If the ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public static final int AvgMinMin = -1;

    /**
     * An artificial score of Average Minus for the North-South pair and Average for the East-West
     * pair.
     */
    public static final int AvgMinAvg = -2;

    /**
     * An artificial score of Average Minus for the North-South pair and Average Plus for the East-West
     * pair if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public static final int AvgMinPlus = -3;

    /**
     * An artificial score of Average for the North-South pair and Average Minus for the East-West pair
     * if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public static final int AvgAvgMin = -4;

    /**
     * An artificial score of Average for the North-South pair and Average for the East-West pair.
     */
    public static final int AvgAvgAvg = -5;

    /**
     * An artificial score of Average for the North-South pair and Average Plus for the East-West pair
     * if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public static final int AvgAvgPlus = -6;

    /**
     * An artificial score of Average Plus for the North-South pair and Average Minus for the East-West
     * pair if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public static final int AvgPlusMin = -7;

    /**
     * An artificial score of Average Plus for the North-South pair and Average for the East-West pair
     * if the ScoringDirection property is ScoringDirection_NS or ScoringDirection_NSEW. If the
     * ScoringDirection is ScoringDirection_EW then the values are reversed.
     */
    public static final int AvgPlusAvg = -8;

    /**
     * An artificial score of Average Plus for the North-South pair and Average Plus for the East-West
     * pair.
     */
    public static final int AvgPlusPlus = -9;

    /**
     * Required.The guid of the session the result belongs to.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required, the letters of the section in which the result was obtained. The section must exist.
     */
    @JsonProperty("SectionLetters")
    public String sectionLetters;

    /**
     * Required, must be greater than zero. The table must exist.
     */
    @JsonProperty("TableNumber")
    public int tableNumber;

    /**
     * Required, must be greater than zero. The round must exist.
     */
    @JsonProperty("RoundNumber")
    public int roundNumber;

    /**
     * Required, must be greater than zero. The board must exist, i.e.: it must have been specified in
     * the RoundDTO's LowBoardNumber and HighBoardNumber properties.
     */
    @JsonProperty("BoardNumber")
    public int boardNumber;

    /**
     * Required. The pair for which the result will count towards their result. 1: NortSouth 2:
     * EastWest 3: For NorthSouth as wel as for EastWest Note: currently split scores (scores different
     * for NS and EW) are not supported. BCS will work with the NS value.
     */
    @JsonProperty("ScoringDirection")
    public int scoringDirection;

    /**
     * Marks the result as deleted. All properties below will be ignored.
     */
    @JsonProperty("IsDeleted")
    public boolean isDeleted;

    /**
     * Required: The pairnumber for NorthSouth
     */
    @JsonProperty("PairNorthSouth")
    public int pairNorthSouth;

    /**
     * Required:The pairnumber for EastWest
     */
    @JsonProperty("PairEastWest")
    public int pairEastWest;

    /**
     * Required: either the PairNorthSouth or the PairEastwest number.
     */
    @JsonProperty("DeclaringPair")
    public int declaringPair;

    /**
     * The direction of the declarer: 0: NA 1: North or NorthSouth 2: East or EastWest 3: South 4: West
     */
    @JsonProperty("DeclarerDirection")
    public int declarerDirection;

    /**
     * The contract level: 1-7 natural contract 0 Pass -1 Avg-/Avg- -2 Avg-/Avg -3 Avg-/Av+ -4 Avg/Avg-
     * -5 Avg/Avg -6 Avg/Avg+ -7 Avg+/Avg- -8 Avg+/Avg -9 Avg+/Avg+ -10 No play
     */
    @JsonProperty("Level")
    public int level;

    /**
     * The denomination: 0: NA 1: Clubs 2: Diamonds 3: Hearts 4: Spades 5: NoTrump
     */
    @JsonProperty("Denomination")
    public int denomination;

    /**
     * The stake of the contract: 0: normal 1: doubled 2: redoubled
     */
    @JsonProperty("Stake")
    public int stake;

    /**
     * A number between 0 and 13 describing the number of tricks made. Zero tricks can also mean: pass,
     * or artificial result (see Level)
     */
    @JsonProperty("TotalTricks")
    public int totalTricks;

    /**
     * Optional: 2-10: the card value 11: Jack 12: Queen 13: King 14: Ace
     */
    @JsonProperty("LeadCardRank")
    public int leadCardRank;

    /**
     * Required when LeadCardRank > 0 1: Clubs 2: Diamonds 3: Hearts 4: Spades
     */
    @JsonProperty("LeadCardSuit")
    public int leadCardSuit;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
