// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The RoundDTO describes the seating for a round on a table: the NS and EW pairs and the board numbers
 * expressed by the LowBoardNumber and HighBoardNumber properties.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class RoundDTO {
    /**
     * Required. The guid of the session the round belongs to.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required, the letters of the section.
     */
    @JsonProperty("SectionLetters")
    public String sectionLetters;

    /**
     * Required, must be greater than zero.
     */
    @JsonProperty("TableNumber")
    public int tableNumber;

    /**
     * Required, must be greater than zero.
     */
    @JsonProperty("RoundNumber")
    public int roundNumber;

    /**
     * Optional, can be zero if the table is empty (has no pairs) or is a sit-out (One pair is absent).
     */
    @JsonProperty("LowBoardNumber")
    public int lowBoardNumber;

    /**
     * Optional, can be zero if the table is empty (has no pairs) or is a sit-out (One pair is absent).
     */
    @JsonProperty("HighBoardNumber")
    public int highBoardNumber;

    /**
     * Required, can be zero if the table is empty or the opponents have a sit-out.
     */
    @JsonProperty("PairNS")
    public int pairNS;

    /**
     * Required, can be zero if the table is empty or the opponents have a sit-out.
     */
    @JsonProperty("PairEW")
    public int pairEW;

    /**
     * Optional. The number of the team the NS pair belongs to.
     */
    @JsonProperty("TeamNS")
    public int teamNS;

    /**
     * Optional. The number of the team the EW pair belongs to.
     */
    @JsonProperty("TeamEW")
    public int teamEW;

    /**
     * Optional. The letters of the section where the teammates play the same boards. If used the
     * MatesTableNumber and MatesTableRoundNumber properties must be set as well.
     */
    @JsonProperty("MatesTableSectionLetters")
    public String matesTableSectionLetters;

    /**
     * Optional. The number of the table where the teammates play the same boards. If used the
     * MatesTableSectionLetters and MatesTableRoundNumber properties must be set as well.
     */
    @JsonProperty("MatesTableTableNumber")
    public int matesTableTableNumber;

    /**
     * Optional. The number of the round where the teammates play the same boards. If used the
     * MatesTableSectionLetters and the MatesTableNumber properties must be set as well.
     */
    @JsonProperty("MatesTableRoundNumber")
    public int matesTableRoundNumber;

    /**
     * Currently not in use for scoring programs. Used for internal administration when handling
     * movement updates.
     */
    @JsonProperty("Updated")
    public boolean updated;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
