// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1040.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class carries both a command and its associated data (if any) for the Data Connector. If the
 * command pertains to a specific session the SessionGuid property has to be set. Validation will check
 * in that case if the SessionGuid properties of the SerializedData has the same value. The Data
 * Connector always responds with a ScoringProgramResponse
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ScoringProgramRequest {
    /**
     * Required. The command that the Data Connector must pass on to BCS.
     */
    @JsonProperty("Command")
    public ScoringProgramDataConnectorCommands command = ScoringProgramDataConnectorCommands.None;

    /**
     * Required when using the http interface for the dataconnector
     */
    @JsonProperty("ClubId")
    public String clubId;

    /**
     * Required when using the http interface for the dataconnector
     */
    @JsonProperty("LicenceKey")
    public String licenceKey;

    /**
     * Required if the command pertains to a session. Must be empty otherwise.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * The data associated with the command, if any. Must be serialized as JSON.
     */
    @JsonProperty("SerializedData")
    public String serializedData;
}
