// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class carries the response data that the Data Connector sends back after sending it a
 * ScoringProgramRequest.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class ScoringProgramResponse {
    /**
     * The command of the request that this is the reponse for.
     */
    @JsonProperty("RequestCommand")
    public ScoringProgramDataConnectorCommands requestCommand = ScoringProgramDataConnectorCommands.None;

    /**
     * Specifies the datatype to deserialize to after reception of the response.
     * DataConnectorResponseData.Error signals that something went wrong. The serialized data in that
     * case will be a string describing the error.
     */
    @JsonProperty("DataType")
    public DataConnectorResponseData dataType = DataConnectorResponseData.None;

    /**
     * If the response contains queue data the id of last added queueitem.
     */
    @JsonProperty("LastQueueItemId")
    public int lastQueueItemId;

    /**
     * Specifies the type of error that occurred. ErrorType.None if all went well.
     */
    @JsonProperty("ErrorType")
    public ErrorType errorType = ErrorType.None;

    /**
     * The guid of the session the response belongs to.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * The serialized data. The DataType property tells to what class it should be deserialized.
     */
    @JsonProperty("SerializedData")
    public String serializedData;
}
