// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * This class is a container for participants that can potentially meet each other during the session.
 * Their results will be compared and they will be ranked against each other. Note: if the section is
 * part of a scoringgroup together with an other section the scoring calculation will treat these
 * sections as one.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SectionDTO {
    /**
     * The section hosts a pairs competition. Rankings will be for each pair.
     */
    public static final int GameType_Pairs = 10;

    /**
     * The section hosts an individual competition. Rankings will be for each player.
     */
    public static final int GameType_Individual = 20;

    /**
     * The section hosts a teams competition. Rankings will be for each teams (although a parallel
     * pairs ranking is possible).
     */
    public static final int GameType_Teams = 30;

    /**
     * Required. The guid of the session the section is part of. A string built from a Guid, without
     * the curly braces or connecting dashes. The letters must be capitals
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required, the number of the scoringgroup the section belongs to. Must be greater than zero.
     */
    @JsonProperty("ScoringGroupNumber")
    public int scoringGroupNumber;

    /**
     * Required. The letters of the section. They must be unique within an event. Can be A-Z, AA, BB,
     * CC,...ZZ, AAA, BBB, CCC, ... ZZZ
     */
    @JsonProperty("Letters")
    public String letters;

    /**
     * Optional.
     */
    @JsonProperty("Name")
    public String name;

    /**
     * Required: either 1 or 2.
     */
    @JsonProperty("Winners")
    public int winners;

    @JsonProperty("GameType")
    public int gameType;

    /**
     * Negative value: the eastwest pairs move down the specified number of tables before play starts.
     * Positive value: the eastwest pairs move up the specified number of tables before play starts.
     * Zero: the eastwest pairs do not move. Currently not supported.
     */
    @JsonProperty("EWMoveBeforePlay")
    public int eWMoveBeforePlay;

    /**
     * Optional. A pair that is missing throughout the movement. Alternatively this can be specified by
     * Leaving out the opponent for a pair that would have met the missing pair. However, BCS will be
     * able to discern a sit-out table from an empty table if this value is used. When using a two
     * winner movement a positive number denotes a missing NS pair, a negative value denotes a missing
     * EW pair.
     */
    @JsonProperty("MissingPair")
    public int missingPair;

    /**
     * When "true" the Bridgemate (2) server will be instructed to net close the session when the
     * result for the last available round have been received. In this way it is possible to play Swiss
     * matches.
     */
    @JsonProperty("KeepBridgematesAlive")
    public boolean keepBridgematesAlive;

    /**
     * If true the NorthSouthPairSectionLetters and the EastWestPairSectionLetters must have the value
     * for an existing section.
     */
    @JsonProperty("IsCombiSection")
    public boolean isCombiSection;

    /**
     * Required if IsCombiSection is True. Must be the letters for an existing section. The letters of
     * the section the North-South pairs in the combisection originate from.
     */
    @JsonProperty("NorthSouthPairSectionLetters")
    public String northSouthPairSectionLetters;

    /**
     * Required if IsCombisection is True. Must be the letters for an existing section. The letters of
     * the section the East-West pairs in the combisection originate from.
     */
    @JsonProperty("EastWestPairSectionLetters")
    public String eastWestPairSectionLetters;

    /**
     * Optional, defaults to false. When true the scoring program specifies the seating for every round
     * of this section explicitly through ParticipationDTOs with their RoundNumber set, and BCS will
     * store these participations exactly as sent, without calculating seatings from the movement. Use
     * this for individual sessions and other formats where partnerships change between rounds. When
     * false (the default) participations may only carry round number zero or one and BCS calculates
     * the other rounds from the movement. The value is fixed when the section is created: a later
     * SectionUpdateDTO must carry the same value.
     */
    @JsonProperty("HasExplicitParticipations")
    public boolean hasExplicitParticipations;

    /**
     * An array of TableDTOs. All tables for the section must be specified.
     */
    @JsonProperty("Tables")
    public TableDTO[] tables;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
