// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Contains information for an updated or added section
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SectionUpdateDTO {
    /**
     * Required. The guid of the session the section is part of. A string built from a Guid, without
     * the curly braces or connecting dashes. The letters must be capitals
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required when using the http interface for the dataconnector
     */
    @JsonProperty("ClubId")
    public String clubId;

    /**
     * Required, the number of the scoringgroup the section belongs to. Must be greater than zero. If
     * the scoringgroup already exists the section wull be added to it, otherwise a new scoringgroup
     * wil be added.
     */
    @JsonProperty("ScoringGroupNumber")
    public int scoringGroupNumber;

    /**
     * Must be set and must match the scoringmethod of the scoringgroup if the section is added to one,
     * otherwise it will specify the scoringmethod for the new scoringgroup. See for valid values the
     * ScoringType contstants in the ScoringGroupDTO.
     */
    @JsonProperty("ScoringGroupScoringMethod")
    public int scoringGroupScoringMethod;

    /**
     * Required. The letters of the section. If a section with this letters already exists it will be
     * updated. Otherwise the section will be added. Can be A-Z, AA, BB, CC,...ZZ, AAA, BBB, CCC, ...
     * ZZZ
     */
    @JsonProperty("Letters")
    public String letters;

    /**
     * Optional.
     */
    @JsonProperty("Name")
    public String name;

    /**
     * Required: either 1 or 2.
     */
    @JsonProperty("Winners")
    public int winners;

    @JsonProperty("GameType")
    public int gameType;

    /**
     * Negative value: the eastwest pairs move down the specified number of tables before play starts.
     * Positive value: the eastwest pairs move up the specified number of tables before play starts.
     * Zero: the eastwest pairs do not move. Currently not supported.
     */
    @JsonProperty("EWMoveBeforePlay")
    public int eWMoveBeforePlay;

    /**
     * Optional. A pair that is missing throughout the movement. Alternatively this can be specified by
     * Leaving out the opponent for a pair that would have met the missing pair. However, BCS will be
     * able to discern a sit-out table from an empty table if this value is used. When using a two
     * winner movement a positive number denotes a missing NS pair, a negative value denotes a missing
     * EW pair.
     */
    @JsonProperty("MissingPair")
    public int missingPair;

    /**
     * When "true" the Bridgemate (2) server will be instructed to net close the session when the
     * result for the last available round have been received. In this way it is possible to play Swiss
     * matches.
     */
    @JsonProperty("KeepBridgematesAlive")
    public boolean keepBridgematesAlive;

    /**
     * If true the SitoutSectionLetters must have the value for an existing section.
     */
    @JsonProperty("IsCombiSection")
    public boolean isCombiSection;

    /**
     * Required if IsCombiSection is True. Must be the letters for an existing section. The letters of
     * the section the North-South pairs in the combisection originate from.
     */
    @JsonProperty("NorthSouthPairSectionLetters")
    public String northSouthPairSectionLetters;

    /**
     * Required if IsCombisection is True. Must be the letters for an existing section. The letters of
     * the section the East-West pairs in the combisection originate from.
     */
    @JsonProperty("EastWestPairSectionLetters")
    public String eastWestPairSectionLetters;

    /**
     * Marks the section for deletion. No tables must be specified. ALl properties other than the
     * SessionGuid an Letters are ignored.
     */
    @JsonProperty("IsDeleted")
    public boolean isDeleted;

    /**
     * Optional. Any players that have been added and were not included while initializing the session.
     */
    @JsonProperty("AddedPlayers")
    public PlayerDataDTO[] addedPlayers;

    /**
     * Required, must match the value the section was created with. When true the update must carry the
     * complete seating for all rounds in Participations: BCS replaces the stored participations for
     * the section with the ones in this update and does not calculate seatings from the movement. See
     * HasExplicitParticipations.
     */
    @JsonProperty("HasExplicitParticipations")
    public boolean hasExplicitParticipations;

    /**
     * Optional for a section without explicit participations: the players as they are seated in the
     * first round. Be sure to include players as well that do not play in the first round. Required
     * for a section with HasExplicitParticipations set: the complete seating for all rounds, one
     * ParticipationDTO per (table, round, position). BCS replaces the section's stored participations
     * with this set.
     */
    @JsonProperty("Participations")
    public ParticipationDTO[] participations;

    /**
     * An array of TableDTOs. All tables for the section must be specified. If the section is to be
     * deleted, no tables must be specified.
     */
    @JsonProperty("Tables")
    public TableDTO[] tables;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
