// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1039.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A group of sections that are usually played at the same time and place. Pairs will subscribe to
 * participate in a specific session. If BCS has to administer more than one session at the same time,
 * these sessions must share a comment EventGuid property.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SessionDTO {
    /**
     * Required, must be at least one.
     */
    @JsonProperty("ScoringGroups")
    public ScoringGroupDTO[] scoringGroups;

    /**
     * Optional. A string built from a Guid, without the curly braces or connecting dashes. The letters
     * must be capitals Must be unique if used.
     */
    @JsonProperty("EventGuid")
    public String eventGuid;

    /**
     * Required.A string built from a Guid, without the curly braces or connecting dashes. The letters
     * must be capitals Must be unique
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required. The name of the session.
     */
    @JsonProperty("Name")
    public String name;

    /**
     * Required. The year in which the session is played.
     */
    @JsonProperty("Year")
    public int year;

    /**
     * Required. The month in which the session is played.
     */
    @JsonProperty("Month")
    public int month;

    /**
     * Required. The day on which the session is played.
     */
    @JsonProperty("Day")
    public int day;

    /**
     * Optional. The starting hour for the session.
     */
    @JsonProperty("Hour")
    public int hour;

    /**
     * Optional. The starting minutes for the session.
     */
    @JsonProperty("Minute")
    public int minute;

    /**
     * If True will show the session in the Bridgemate App, if the Bridgemae App has been configured in
     * BCS.
     */
    @JsonProperty("ShowInApp")
    public boolean showInApp;

    @JsonProperty("EWReturnHome")
    public boolean eWReturnHome;

    @JsonProperty("PairsMoveAccrossField")
    public boolean pairsMoveAccrossField;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
