// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1041.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A class describing a real or virtual bridge table where each round two pairs will compete.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class TableDTO {
    /**
     * Required. The guid of the session the table belongs to.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required, the letters of the section the table belongs to. The section must exist.
     */
    @JsonProperty("SectionLetters")
    public String sectionLetters;

    /**
     * Required, must be greater than zero and must be unique within the section.
     */
    @JsonProperty("TableNumber")
    public int tableNumber;

    /**
     * Optional: specifies if the Bridgemate on the table should work in online mode (default) or
     * offline mode. In offline mode the Bridgemate will not communicate with the Bridgemate 3 server
     * during the session, but will try to send its results after the last board had been played.
     * Because of this the Bridgemate will not respond to movement updates. Mind: this setting will
     * only have effect when the Bridgemate first connects to the session. Once a Bridgemate has been
     * initialized with movement data the ConnectionMode cannot be changed until the Bridgemate is
     * restarted.
     */
    @JsonProperty("ConnectionMode")
    public Bm3ConnectionModeOption connectionMode = Bm3ConnectionModeOption.Online;

    /**
     * If set to "True" the Bridgemates will await new rounddata after all results have been entered
     * for the existing rounds on the tables. Otherwise, by default, the Bridgemate will signal end of
     * session when all the results its expects have been entered.
     */
    @JsonProperty("KeepBridgematesAlive")
    public boolean keepBridgematesAlive;

    /**
     * Required. An array of RoundDTOs describing which pairs will meet on this table and which boards
     * they will play.
     */
    @JsonProperty("Rounds")
    public RoundDTO[] rounds;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
