// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Specifies the positions on a table.
 */
public enum TableDirection {
    /**
     * No position specified.
     */
    None(0),
    /**
     * North
     */
    North(1),
    /**
     * East
     */
    East(2),
    /**
     * South
     */
    South(3),
    /**
     * West
     */
    West(4);

    private final int value;

    TableDirection(int value) {
        this.value = value;
    }

    @JsonValue
    public int getValue() {
        return value;
    }

    /**
     * Maps a wire value back to the enum. Unknown values (from a newer Data Connector)
     * map to None instead of failing the whole response.
     */
    @JsonCreator
    public static TableDirection fromValue(int value) {
        for (TableDirection member : values()) {
            if (member.value == value) {
                return member;
            }
        }
        return None;
    }
}
