// Generated by tools/DtoGenerator from BridgeSystems.Bridgemate.DataConnector.ScoringProgramClient 5.0.1036.0. Do not edit by hand.
package nl.bridgemate.dataconnector.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Contains information about a TD call.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class TdCallDTO {
    /**
     * The TD call status has been iniiated.
     */
    public static final int TdCallStatus_Launched = 1;

    /**
     * The TD is at the table.
     */
    public static final int TdCallStatus_InProgress = 2;

    /**
     * The call has been resolved.
     */
    public static final int TdCallStatus_Resolved = 3;

    /**
     * Resolution of the call has been deferred.
     */
    public static final int TdCallStatus_Deferred = 4;

    /**
     * Required. The guid of the session the td call belongs to.
     */
    @JsonProperty("SessionGuid")
    public String sessionGuid;

    /**
     * Required, the letters of the section the td call belongs to. The section must exist.
     */
    @JsonProperty("SectionLetters")
    public String sectionLetters;

    /**
     * Required, the table in the section where the td call originates from.
     */
    @JsonProperty("TableNumber")
    public int tableNumber;

    /**
     * Required. The round om the table where the td call is generated from.
     */
    @JsonProperty("RoundNumber")
    public int roundNumber;

    /**
     * The hour at which the td call was generated. Use 24 hours to a day.
     */
    @JsonProperty("Hour")
    public int hour;

    /**
     * The minute in which the td call was generated.
     */
    @JsonProperty("Minute")
    public int minute;

    /**
     * Required. Valid values are: 1: Launched 2: InProgress 3. Resolved 4: Deferred
     */
    @JsonProperty("Status")
    public int status;

    /**
     * An array of messages describing problems in data integrity and invalid values.
     */
    @JsonProperty("ValidationMessages")
    public String[] validationMessages;
}
